### ISSUE TITLE
[bug] Wrong collab link for preprocessing and brats toolkit

### ISSUE THREAD

**Issue by MarcelRosier** [BrainLesion/tutorials#38]
the open in collab button opens the aurora repo notebook, links can be generated [here](https://openincolab.com/)

**Comment by neuronflow** [comment]
Yes, is there a way to autogenerate links?

**Comment by MarcelRosier** [comment]
> Yes, is there a way to autogenerate links?

maybe, but i dont think it's needed since it's justing modifying a single line, would not over engineer this.

**Comment by neuronflow** [comment]
@evamariie can you please try to fix this?

**Comment by evamariie** [comment]
Hi, I checked the colab link for [BraTS Toolkit](https://github.com/BrainLesion/tutorials/blob/main/BraTS-Toolkit/glioma_segmentation_with_BraTS_Toolkit.ipynb), for me it points to https://colab.research.google.com/github/BrainLesion/tutorials/blob/main/BraTS-Toolkit/glioma_segmentation_with_BraTS_Toolkit.ipynb

I fixed the wrong link in preprocessing, see #48
