### ISSUE TITLE
AURORA tutorial: Error when using VANILLA version in ModelSelection 

### ISSUE THREAD

**Issue by evamariie** [BrainLesion/tutorials#43]
AURORA tutorial: 
I added a line to select the respective model (VANILLA, BEST, LAST) in the notebook.  

BEST and LAST work but there is an Error when I use the VANILLA version in the ModelSelection. 
[Error_Vanilla.txt](https://github.com/BrainLesion/tutorials/files/14736188/Error_Vanilla.txt)

**Comment by neuronflow** [comment]
This seems to behave as expected as the vanilla model is only available for the combination of all 4 modalities. Reopen if needed :)
