### ISSUE TITLE
[feature request] mention ereg in preprocessing tutorial

### ISSUE THREAD

**Issue by neuronflow** [BrainLesion/tutorials#49]
see above :)

**Comment by evamariie** [comment]
I saw the TODO in issue [#72](https://github.com/BrainLesion/preprocessing/issues/72) first and opened #50 for the new branch
Sry, I will do it within this (#49) open issue next time

**Comment by evamariie** [comment]
Was fixed in issue #50 but needs review (@neuronflow )
