### ISSUE TITLE
[panoptica] images in tutorials are not displayed

### ISSUE THREAD

**Issue by neuronflow** [BrainLesion/tutorials#9]
see above

**Comment by MarcelRosier** [comment]
GitHub seems unable to render \<img> html tags in notebook previews.
The markdown syntax (\!\[]\()) however does as of now not support resizing the image to a reasonable height that fits into the notebook.
As a workaround we use the markdown syntax and store die images directly in the desired resolution.
Also hyperlinks as img src were not able to be rendered, hence the fiugres were added directly to this repo.

This currently leads to file duplication between the tutorials and panoptica repos.
To avoid this the figure references in the panoptica repo could be changed to point to the figures in this repo as long as there are no notebooks in the panoptica repo itself that need to display the figures.
